version: '2'
services:
  web:
    image: portfolio
    volumes:
    - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"